##
# Society: ARKultur
# ARKultur EIP, 2021
#
# Author:
# Maxime P.
# File name:
# python-app.yml
#
# Description:
# [Change]
##

name: Python application

on:
  push:
    branches:
      - develop

jobs:
  utests:
    name: Run Pytest

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      description: Checkout the last commit
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov

    - name: Start Unit Test
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov="./utests/" -cov-report=xml --cov-report=html

    - name: Upload Unit Test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./htmlcov/

    - name: Create pull request # if utests passed
      if: ${{ success() }}
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "The name of the pusher: ${{ github.event.pusher.name }}"
        echo "The email of the pusher: ${{ github.event.pusher.email }}"